### ISSUE TITLE
API Token ?

### ISSUE THREAD

**Issue by fgallese** [Snowfire01/Wallet.Api.Net#1]
Hello,

Thank you for sharing this app.

I was reading the instructions to get the token, but I cannot find this:

`Settings -> Advanced Settings -> REST API`

Any idea if this was removed or moved somewhere else ?

**Comment by h4nney** [comment]
They removed api few months ago.

**Comment by leonschreiber96** [comment]
I didn't know that, since I haven't been using the App for a while now. I'm sad to hear this, but thank you for the information!
